#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd -c ~/.config/sxhkd/sxhkdrc &
~/.config/polybar/launch.sh &

bspc monitor -d 1 2 3 4 5 6 7 8 9

#### BSPWM configuration ####
#bspc config border_radius                8
bspc config border_width									3
bspc config borderless_monocle            true
bspc config bottom_padding                0
bspc config click_to_focus                true
bspc config focus_by_distance             true
bspc config focus_follows_pointer         true
bspc config gapless_monocle               true
bspc config history_aware_focus           true
bspc config left_padding                  0
bspc config merge_overlapping_monitors    true
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config pointer_modifier mod4
bspc config remove_disabled_monitors      true
bspc config right_padding                 0
bspc config single_monocle                false
bspc config split_ratio                   0.50
bspc config top_padding                   0
bspc config window_gap                    12

#### BSPWM coloring ####
bspc config normal_border_color		      "#000000"
bspc config active_border_color	        "#1e1e1e"
bspc config focused_border_color	      "#caa9fa"
bspc config presel_feedback_color	      "#caa9fa"
bspc config urgent_border_color 	      "#caa9fa"

# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off
