#!/usr/bin/env bash

## DISK
hdd() {
  # hdd="$(df -h | awk 'NR==4{print $3, $5}')"
  hdd="$(df -h | awk 'NR==4{print $3}')"
  echo -e "$hdd"
}

## RAM
mem() {
  # mem=`free | awk '/Mem/ {printf "%dM/%dM\n", $3 / 1024.0, $2 / 1024.0 }'`
  mem="$(free | awk '/Mem/ {printf "%dM%dM\n", $3 / 1024.0}')"
  echo -e "$mem"
}

## CPU
cpu() {
  read cpu a b c previdle rest < /proc/stat
  prevtotal=$((a+b+c+previdle))
  sleep 0.5
  read cpu a b c idle rest < /proc/stat
  total=$((a+b+c+idle))
  cpu=$((100*( (total-prevtotal) - (idle-previdle) ) / (total-prevtotal) ))
  # echo -e "033[31m💻 $cpu%\e[0m"
  echo -e "$cpu%"
}

## VOLUME
vol() {
    # vol=`amixer get Master | awk -F'[][]' 'END{ print $4":"$2 }' | sed 's/on://g'`
    vol=`amixer get Master | awk -F'[][]' 'END{ print $2 }' | sed 's/on://g'`
    echo -e "$vol"
}

SLEEP_SEC=3
#loops forever outputting a line every SLEEP_SEC secs

# It seems that we are limited to how many characters can be displayed via
# the baraction script output. And the the markup tags count in that limit.
# So I would love to add more functions to this script but it makes the
# echo output too long to display correctly.

# \e[1;31m
# reset = 0, black = 40, red = 41, green = 42, yellow = 43, blue = 44, magenta = 45, cyan = 46, and white=47, are the commonly used color
alias vim='nvim'
while true
do
	BAT=$(acpi -b | awk 'NR==2 { print $4 }' | tr -d ',')
	DATE=$(date +"%F %R")
    # xsetroot -name "+@fg=1; +@fn=1;💻+@fn=0; $(cpu) +@fg=0; | +@fg=2; +@fn=1;💾+@fn=0; $(mem) +@fg=0; | +@fg=3; +@fn=1;💿+@fn=0; $(hdd) +@fg=0; | +@fg=4; +@fn=1;🔈+@fn=0; $(vol) +@fg=0; |"
    xsetroot -name " 💻 $(cpu) | 🖥️ $(mem) | 💾 $(hdd) | 🎧 $(vol) | ⚡ $BAT | $DATE "
	sleep $SLEEP_SEC
done &

# Launch programs
xcompmgr -c &
feh --bg-fill ~/Pictures/Rama.jpg &
dunst &

# mpd &>/dev/null &
# dropbox start &>/dev/null &
# redshift -l 12.9667:77.5667 -t 3700:3700 &>/dev/null &
# trayer --edge bottom --align right --SetDockType true \
# --SetPartialStrut true --expand true --widthtype percent \
# --width 100 --height 25 &>/dev/null &
# sudo nm-applet &>/dev/null &
# while true
# do
#     DATE=$(date +"%Y-%m-%d %I:%M")
#     BAT=$(acpi -b | awk '{ print $4 }' | tr -d ',')
#     xsetroot -name "B$BAT $DATE"
#     sleep 1
# done &
# # verbar &
exec dwm
