#!/usr/bin/env bash
# If internet connection is not available, exit
if ! ping -c 1 archlinux.org &> /dev/null; then
		exit 1
fi

# Check updates from the official repositories
official_updates=$(paru -Qu | wc -l)

# Check updates from the AUR
aur_updates=$(paru -Qua | wc -l)

printf " %s" $(($official_updates + $aur_updates))
