#!/usr/bin/env bash

input=$(echo "" | dmenu)
result=$(awk "BEGIN{ print $input }")
notify-send $result
printf $result | xclip -sel clip

# # Prompt for a calculation
# calculation=$(echo | dmenu)
#
# # Check if the input is non-empty
# if [ -z "$calculation" ]; then
#     # notify-send "No calculation entered"
#     exit 1
# fi
#
# # Perform the calculation using bc, with rounding to 5 decimal places
# result=$(echo "scale=6; $calculation" | bc -l | xargs printf "%.*f" 5)
#
# # Use awk to remove unnecessary trailing zeros and decimal point if the result is an integer
# formatted_result=$(echo $result | awk '{print ($0 + 0)}')
#
# # Check if the calculation was successful
# if [ $? -ne 0 ]; then
#     # notify-send "Calculation error"
#     exit 1
# fi
#
# # Show the result with notify-send
# notify-send "$formatted_result"
#
# # Copy the result to the clipboard
# echo -n $formatted_result | xclip -selection clipboard
