#!/usr/bin/env bash

# if $1 is empty, then exit
if [ -z "$1" ]; then
		echo "Needs authcode as argument"
		exit 1
fi

rm ~/.calcurse/apts
rm -rf ~/.calcurse/notes
calcurse-caldav --init=two-way --authcode="$1"
