#!/usr/bin/env bash

checkDependencies() {
	programs=("python" "dialog" "dropbox" "wget")
	for program in "${programs[@]}"
	do
		if [[ ! $(pacman -Qq $program) ]]
		then
			echo "$program is not installed"
			read -p "Install dependency $program? [y/n] " -n 1 -r
			if [[ $REPLY =~ ^[Yy]$ ]]
			then
				sudo pacman -S $program
			fi
		fi
	done
}

getDropboxScripts() {
	script=~/.local/bin/dropbox.py
	if [ ! -d ~/.local/bin ]; then
		mkdir -p ~/.local/bin;
	fi
	if [ ! -f $script ]; then
		wget "https://linux.dropbox.com/packages/dropbox.py" -O $script
		# renaming deprecated function
		sed 's/isSet/is_set/g' $script > $script.new
		mv $script.new $script
	fi

	uploader=~/.local/bin/dropbox_uploader.sh
	if [ ! -f $uploader ]; then
		wget https://raw.githubusercontent.com/andreafabrizi/Dropbox-Uploader/master/dropbox_uploader.sh -O $uploader
		chmod +x $uploader
	fi
}
