#!/usr/bin/env bash
# modified script from https://superuser.com/questions/36645/how-to-rotate-images-automatically-based-on-exif-data

ifinstalled jhead

for f in $@
do
	orientation=$(jhead -v "$f" | sed -nr 's:.*Orientation = ([0-9]+).*:\1:p')
	orientation=$(echo $orientation | cut -c1-1)
	# echo $orientation
	if [ $orientation -gt 1 ];
	then
		echo Rotating "$f"...
		convert -auto-orient "$f" "$f"
	fi
done
