#!/usr/bin/env bash
STATUS=$(mullvad status | awk '{print $1}')
if [[ $STATUS == "Connected" ]]; then
	nohup brave --private-window "https://duckduckgo.com" &
else
  nohup firefox --new-window "https://youtube.com/" &
fi
