#!/usr/bin/env bash

# Define the array of supported file types
declare -a filetypes=("3gp" "aac" "ac3" "ahx" "aiff" "ape" "dts" "flac" "flac" "hes" "it" "m4a" "m4p" "m4r" "mid" "midi" "mka" "mo3" "mod" "mods" "mp3" "mp4" "mpc" "mtm" "nsf" "ogg" "opm" "opus" "psf" "s3m" "scl" "sid" "spc" "spx" "tta" "umx" "vgz" "wav" "win" "wma" "wv" "xm")

# Variable to keep track of the first file added
first=""

# Start fzf and store the selection
selection=$(find ~/Music/ | fzf)

# Check if the selection is not empty
if [[ -n "$selection" ]]; then
    # Check if the selection is a file and in the supported file types
    if [[ -f "$selection" && " ${filetypes[@]} " =~ " ${selection##*.} " ]]; then
        mpc --host ~/.mpd/socket add "$selection"
        # notify-send "Added to MPD: $selection"
        if [[ -z "$first" ]]; then
            first="$selection"
        fi
    elif [[ -d "$selection" ]]; then
        # If the selection is a directory, add all supported files in it
        for file in "$selection"/*; do
            if [[ " ${filetypes[@]} " =~ " ${file##*.} " ]]; then
                mpc --host ~/.mpd/socket add "$file"
                if [[ -z "$first" ]]; then
                    first="$file"
                fi
            fi
        done
        # notify-send "Added directory to MPD: $selection"
    else
        notify-send "Unsupported file type"
    fi
fi

# Play the first song added
if [[ -n "$first" ]]; then
    # Extract just the filename from the path
    filename_only="${first##*/}"
    # Remove the file extension
    filename_only="${filename_only%.*}"
    mpc --host ~/.mpd/socket searchplay filename "$filename_only"
fi
