#!/bin/sh

eval "$(ssh-agent -s)" &> /dev/null
ssh-add ~/.ssh/git &> /dev/null

cd $1
folders=$(find ~+ -mindepth 1 -maxdepth 1 -type d) &> /dev/null
all=false

for folder in $folders
do
	cd $folder
	git remote update
	if [[ $(git status | grep modified) ]]; then
		echo "Changes in $folder"
		# pull from github
		git branch -r | grep -v '\->' | sed "s,\x1B\[[0-9;]*[a-zA-Z],,g" | while read remote; do git branch --track "${remote#origin/}" "$remote"; done;
		git fetch --all;
		git pull --all;
		# if folder contains file config.def.h or config.h
		if [[ -f config.def.h ]] || [[ -f config.h ]]; then
			# compile and install
			make clean install
		fi
		fi
	done

