#!/usr/bin/env bash

ifinstalled bc || exit 1

if [ $# -eq 0 ]
  then
    echo "Need number of minutes as argument" && exit 1
fi

SUM=$(bc<<<"$*")
HOURS=$(bc <<< "$SUM/60")
MINUTES=$(bc <<< "$SUM%60")
echo "$HOURS:$MINUTES"
