#!/usr/bin/env bash

STATUS=$(mullvad status | awk '{print $NF}')
if [[ $STATUS == "Disconnected" ]]; then
    echo "Mullvad not connected"
else
    notify-send "Disconnecting Mullvad"
    mullvad disconnect
    # SUDO_ASKPASS=~/.local/bin/dmenupass sudo -A cpupower frequency-set -g powersave && notify-send 'Powersave CPU governor'
    sleep 2
    nohup mailsync &
fi
