#!/usr/bin/env bash
# save the output from pw-link -lI to an array named links
# remove whitespace from beginning of lines
readarray -t links < <(pw-link -lI | sed 's/^[ \t]*//')
# store name that begins with alsa_output in a variable

# Check if alsa_output.*FL exists
alsaFL=$(printf '%s\n' "${links[@]}" | grep -o -m 1 "alsa_output.*FL")

# Check if alsa_output.*FR exists
alsaFR=$(printf '%s\n' "${links[@]}" | grep -o -m 1 "alsa_output.*FR")

# if array links contains REAPER:out1
if [[ " ${links[@]} " =~ " REAPER:out1 " ]] && [[ ! -z "$alsaFL" ]]; then
	echo "disconnecting $alsaFL"
	pw-link -d REAPER:out1 $alsaFL
fi

# if array links contains REAPER:out2
if [[ " ${links[@]} " =~ " REAPER:out2 " ]] && [[ ! -z "$alsaFR" ]]; then
	echo "disconnecting $alsaFR"
	pw-link -d REAPER:out2 $alsaFR
fi

# if array links doesn't contain bluez_output
if [[ ! " ${links[@]} " =~ " bluez_output " ]]; then
		MAC=$(echo $HEADPHONES | tr ":" "_")
		pw-link REAPER:out1 bluez_output.$MAC.1:playback_FL
		pw-link REAPER:out2 bluez_output.$MAC.1:playback_FR
fi

printf '%s\n' "${links[@]}"#
# #!/usr/bin/env bash
# # save the output from pw-link -lI to an array named links
# # remove whitespace from beginning of lines
# readarray -t links < <(pw-link -lI | sed 's/^[ \t]*//')
# # store name that begins with alsa_output in a variable
#
# # if array links contains REAPER:out1
# if [[ " ${links[@]} " =~ " REAPER:out1 " ]]; then
# 	pw-link -d REAPER:out1 alsa_output.pci-0000_07_00.6.HiFi__hw_Generic_1__sink:playback_FL
# fi
#
# # if array links contains REAPER:out2
# if [[ " ${links[@]} " =~ " REAPER:out2 " ]]; then
# 	pw-link -d REAPER:out2 alsa_output.pci-0000_07_00.6.HiFi__hw_Generic_1__sink:playback_FR
# fi
#
# # if array links doesn't contain bluez_output
# if [[ ! " ${links[@]} " =~ " bluez_output " ]]; then
# 		MAC=$(echo $HEADPHONES | tr ":" "_")
# 		pw-link REAPER:out1 bluez_output.$MAC.1:playback_FL
# 		pw-link REAPER:out2 bluez_output.$MAC.1:playback_FR
# fi
#
# printf '%s\n' "${links[@]}"
