#!/bin/sh
echo "Remapping keys"
# # echo "Loading xresources"
xrdb -load ~/.Xresources &
# echo "Setting capslock to shift"
setxkbmap -option shift:both_capslock_cancel;
# echo "xmodmap"
xmodmap ~/.Xmodmap
# echo "Setting capslock to escape"
xcape -e 'Mode_switch=Escape'
xcape -e 'Caps_Lock=Escape'
# echo "Setting keyboard repeat rate"
xset r rate 300 50 &
# Define an associative array with device names as keys and desired properties as values
declare -A devices
devices=(
  ["TPPS/2 IBM TrackPoint"]="-0.45"
  ["TPPS/2 Elan TrackPoint"]="-0.55"
  ["Synaptics TM3288-011"]="0.3"
  ["SynPS/2 Synaptics TouchPad"]="0.3"
)

# Set properties for devices if they are present
for device in "${!devices[@]}"; do
  # Check if the device is connected
  if xinput list | grep -q "$device"; then
    # Set the "libinput Accel Speed" property for the device
		# echo "Setting ${device} acceleratino speed to ${devices[$device]}"
    xinput set-prop "$device" "libinput Accel Speed" "${devices[$device]}"

    # Additional properties for specific devices can be set here with conditional checks
    if [ "$device" == "Synaptics TM3288-011" ] || [ "$device" == "SynPS/2 Synaptics TouchPad" ]; then
			# echo "Setting ${device} tapping enabled"
      xinput set-prop "$device" "libinput Tapping Enabled" 1
    fi
  fi
done
