#!/usr/bin/env bash
#
# Check if no arguments are provided
if [ $# -eq 0 ]; then
	echo "No files specified."
	exit 1
fi

# Flag for renaming all remaining files
rename_all=false

# Function to confirm action
confirm() {
	if $rename_all; then
		return 0
	fi

	while true; do
		read -p "$1 [Y/N/A]: " yn
		case $yn in
			[Yy]*) return 0;;
			[Nn]*) return 1;;
			[Aa]*) rename_all=true; return 0;;
			*) echo "Please answer yes, no, or all.";;
		esac
	done
}

# Regular expression to match the source format
source_format_regex='Screenshot_([0-9]{8})-([0-9]{6})(.*)\.(png|jpg)'

# Process each file passed as an argument
for file in "$@"; do
	# Check if file matches the source format
	if [[ $file =~ $source_format_regex ]]; then
		# Extract date, time, and file extension
		year=${BASH_REMATCH[1]:0:4}
		month=${BASH_REMATCH[1]:4:2}
		day=${BASH_REMATCH[1]:6:2}
		hour=${BASH_REMATCH[2]:0:2}
		minute=${BASH_REMATCH[2]:2:2}
		second=${BASH_REMATCH[2]:4:2}
		trailing=${BASH_REMATCH[3]}
		extension=${BASH_REMATCH[4]}

				# Format new file name
				newname="${year}-${month}-${day} ${hour}_${minute}_${second}${trailing}.${extension}"

				# Confirmation prompt
				if confirm "Rename $file to $newname"; then
					mv "$file" "$newname"
					echo "Renamed $file to $newname"
				fi
	fi
done
