#!/usr/bin/env bash
notify-send "don't run this script"
# nvim ~/.cache/nvim/scnvim/scnvim_snippets.lua -c ':%s/dscr = "[^"]*"//g | %s/\.new//g | %s/"\(\w\+\):/"\\\\\1.kr(/g | %s/\(i([^"]*"\)\([^"]*\)/\1\2/g | %s/", "/"), "/g | %s/t(")"),}/t("))"),}/g | %s/\(\d*\)\.0/\1/g | wq'
