#!/usr/bin/env bash

# Function to check if the tmux session exists
tmux_has_session() {
  tmux has-session -t $1 2>/dev/null
}

# Start a new tmux session if it doesn't exist
if ! tmux_has_session "main"; then
  tmux new-session -d -s "main"
fi

# # Send 'Ctrl+l' to clear the screen
# tmux send-keys -t "main" C-l

# Start a new kitty terminal and attach to the tmux session
kitty -T tmuxmain tmux attach -t "main" &
